// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AddressAutocompleteController from "./address_autocomplete_controller"
application.register("address-autocomplete", AddressAutocompleteController)

import CarouselController from "./carousel_controller"
application.register("carousel", CarouselController)

import DistanceController from "./distance_controller"
application.register("distance", DistanceController)

import GeolocateController from "./geolocate_controller"
application.register("geolocate", GeolocateController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import MapController from "./map_controller"
application.register("map", MapController)

import NavigationController from "./navigation_controller"
application.register("navigation", NavigationController)

import PassingcoordinatesController from "./passingcoordinates_controller"
application.register("passingcoordinates", PassingcoordinatesController)

import RevealController from "./reveal_controller"
application.register("reveal", RevealController)

import SendrequestController from "./sendrequest_controller"
application.register("sendrequest", SendrequestController)
